config/routes.rb
CityStop::Application.routes.draw do

  devise_for :users

  resources :itineraries

  root :to => "home#index"

  get 'itineraries' => 'itineraries#index', as: :user_root

end

app/models/itinerary.rb
# models#itinerary
class Itinerary < ActiveRecord::Base

  serialize :route, JSON

  belongs_to :user
  # Attributes that user can access
  attr_accessible :description, :name, :time
  # Any Itinerary must have these fields
  validates :user, :name, :time, :route, :kind, presence: true
  # Itinerary can nesting types from array below
  # and must have one of them
  validates :kind,
    inclusion: { in: %w{ cycle pedestrian vechicular } }
  validate :pedestrian_point, :even_route_points,
    :more_than_one_point, :only_float

  # One geopoint have 2 coordinates
  # So the final array can't be odd
  # i.e. [x1, y1, x2, y2] or smthng
  GeoPoint = 2

  def pedestrian_point
    errors.add(:route, 'pedestrians can have only one geopoint') if
      (kind == 'pedestrian') and (route.length != GeoPoint)
  end

  def even_route_points
    # Return if already got errors
    return unless errors.blank?
    errors.add(:route, "can't be odd") if
      route.length % GeoPoint != 0
  end

  def more_than_one_point
    return unless errors.blank?
    errors.add(:route, 'non-pedestrian kind must have at least two points') if
      (route.length < GeoPoint*2) and (kind == 'cycle' or kind == 'vechicular')
  end

  def only_float
    return unless errors.blank?
    route.each do |point|
      errors.add(:route, 'points can only be float') if
        point.class != Float
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,
    :remember_me, :name
  # attr_accessible :title, :body

  validates :name, :presence => true, :uniqueness => true

  has_many :itineraries

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :configure_permitted_parameters, if: :devise_controller?

  after_filter :flash_to_headers

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit :name, :email, :password, :password_confirmation
      end
    end

  private

    def flash_to_headers
      return unless request.xhr?
      response.headers['X-Message'] = flash_message
      response.headers['X-Message-Type'] = flash_type.to_s

      flash.discard # don't show the flash appear after page reload
    end

    def flash_message
      [:error, :warning, :notice].each do |type|
        return flash[type] unless flash[type].blank?
      end
    end

    def flash_type
      [:error, :warning, :notice].each do |type|
        return type unless flash[type].blank?
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  # User shall be signed in
  # to access any of itineraries actions
  before_filter :authenticate_user!

  def index
    # Load all user itineraries on index action
    @itineraries = current_user.itineraries
  end

  def create
    # Build new empty itinerary (params from model, I quess)
    # Then fill it with user data and saving
    itinerary = current_user.itineraries.build(params[:itinerary])
    itinerary.save
    redirect_to itineraries_path
  end

  def edit
    # Load all user itineraries, then searching by id
    @itineraries = current_user.itineraries
    @itinerary = @itineraries.find(params[:id])
  end

  def update
    # I suppose all other actions is self-descriptive
    itinerary = current_user.itineraries.find(params[:id])
    itinerary.update_attributes(params[:itinerary])
    itinerary.save
    redirect_to itineraries_path
  end

  def destroy
    itinerary = current_user.itineraries.find(params[:id])
    itinerary.destroy
    redirect_to itineraries_path
  end

  def show
    @itinerary = current_user.itineraries.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title){ page_title }
  end

  def asset_exist?(asset)
    Rails.application.assets.find_asset(asset)
  end

  def is_active(link_controller)
    params[:controller] == link_controller ? 'active' : nil
  end

end # ApplicationHelper

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = "<ul>#{messages}</ul>"

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/home/index.html.haml
-# Home#index
=title 'Главная'

-content_for :content do
 .col-sm-12
  %h2 Где это я?
  %p= link_to "Зарегестрироваться", new_user_registration_path

app/views/itineraries/_form.html.haml
-# _form

= form_for @itinerary || Itinerary.new do |f|
 = f.label :name, I18n.t(:itinerary_name_field)
 = f.text_field :name
 = f.label :time, I18n.t(:itinerary_time_field)
 = f.text_field :time
 = f.label :description, I18n.t(:itinerary_description_field)
 = f.text_field :description
 = f.submit

app/views/itineraries/edit.html.haml
-# itineraries#edit

- title "Создать маршрут"

- content_for :content do
 = render 'form'

app/views/itineraries/index.html.haml
-# itineraries#index

- title "Маршруты"

- content_for :content do
 
 %table.table.table-hover
  %tbody
   - for itinerary in @itineraries do
    %tr
     %td
      -# Hours before start
      %span.glyphicon.glyphicon-time
      14 ч.
     %td
      -# Soon this will be replace by icon
      = itinerary.kind
     %td.itinerary_name
      = link_to itinerary.name, itinerary_path(itinerary)
     %td.del_form
      = link_to edit_itinerary_path(itinerary) do
       %span.glyphicon.glyphicon-pencil
      = link_to '&times;'.html_safe, '#confirm', class: 'close delete-action', :'data-id' => "#{itinerary.id}", :'data-toggle' => 'modal'
   %tr
    %td#new-one{ colspan: '4' }
     = link_to new_itinerary_path do
      %span#add
       %span.glyphicon.glyphicon-plus
       Добавить маршрут или место

 -# Modal window
 #confirm.modal.fade{ tabindex: '-1', role: 'dialog', :'aria-labelledby' => "Confirm", :'aria-hidden' => 'true' }
  .modal-dialog
   .modal-content
    .modal-header
     %button.close{ type: 'button', :'aria-hidden' => 'true', :'data-dismiss' => 'modal' }
      &times;
     %h4.modal-title
      Подтвердите действие
    .modal-body
     %h2 Удалить?
    .modal-footer
     %button.btn.btn-default{ :'data-dismiss' => 'modal' }
      Нет
     %button#confirm-btn.btn.btn-primary
      -# Find me in itineraries.js.coffee

app/views/itineraries/new.html.haml
-# itineraries#new

- title "Создать маршрут"

- content_for :content do
 = render 'form'

app/views/itineraries/show.html.haml
-# itineraries#show

- title 'Детали'

- content_for :content do
 %h2= @itinerary.name
 %p= @itinerary.time
 %p= @itinerary.description

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "ru"}
 %head

  %meta{:'http-equiv' => "Content-Type", :content => "text/html", :charset => "utf-8"}
  %title= "CityStop | #{content_for(:title)}"
  = favicon_link_tag 'favicon.ico'

  = stylesheet_link_tag    "application", :media => "all"
  /[if lte IE 9]
   = stylesheet_link_tag    "application-ie", :media => "all"

  = javascript_include_tag "application"
  = csrf_meta_tags

 %body

  %nav.navbar.navbar-default.navbar-fixed-top{ role: 'navigation' }
   .container
    =link_to root_path do
     =image_tag 'logo.png', size: '45x45', class: 'navbar-brand', id: 'logo'
    =link_to "CityStop", root_path, class: 'navbar-brand'

    -if user_signed_in?
     %ul#head-nav.nav.navbar-nav
      %li{ class: is_active('home') }
       =link_to "Общая карта", root_path
      %li{ class: is_active('itineraries') }
       =link_to "Мои маршруты", user_root_path

    %p.navbar-text.pull-right
     -if user_signed_in?
      %span.glyphicon.glyphicon-user
      =current_user.name + ' / '
      =link_to "Выйти", destroy_user_session_path, method: :delete
     -else
      =link_to "Войти", new_user_session_path

  .container
   #wrapper.row-fluid
    -if (controller_name == 'itineraries')
     #map-wrapper.well.col-sm-7
      #searchbox
      #map
       %p Here will be a <s>city</s> map!

     #filters.well.col-sm-5
      = render 'shared/flash'
      = yield :content

    -else
     #map-wrapper.well.col-sm-12
      .col-sm-6.col-sm-offset-3= render 'shared/flash'
      = yield :content

app/views/shared/_flash.haml
- if notice || alert
 #flash-message.alert.alert-block.alert-danger.fade.in
  %button.close{ type: 'button', :'data-dismiss' => 'alert', :'area-hidden' => 'true' }
   &times;
  - flash.each do |name, msg|
   = content_tag :div, msg, id: "flash_#{name}"